### PR TITLE
Rework of the tilt_scan task.

### PR DESCRIPTION
**Pull request by skasperski**
- removed deprecated envire output
- cleaner usage of rock transformer
- allows to capture point clouds in both directions

### CODE REVIEW

**Comment by leifole** [comment]
Ok, lot's of changes. Have you tested them on a robot?

**Comment by skasperski** [comment]
I tested it on the simulated Coyote-III, where it works nicely. Still waiting for some time to test it on the real Coyote-III.

**Comment by leifole** [comment]
ok, than let's wait until it was tested there.

**Comment by skasperski** [comment]
Tested on Coyote now, where it is also working.

**Comment by jmachowinski** [comment]
Nice cleanup, only the indentation is broken now. 
Please use tabwitdh 8 and replace the tabs by 4 spaces ;-)

**Comment by jmachowinski** [comment]
And the try catch blocks around the _odometry2body.get(mLastScanTime, odometry2body, true)
are looking weired to me.

**Pull request merged**
